input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/data/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/segmentation/"
experiment = "Fluo-C3DL-MDA231"
dataset = "01_cells"
overwrite = false
merge_thresholds = [ 1.0,]
skip_merges = true
exp_uid = "fs1cpm6_seg_nomrg"

[seg_params]
seg_method = "cellpose"
spot_sigma = 3.0
outline_sigma = 1.0

[affinity_params]
smoothing = [ 1, 1, 1,]
neighborhood = [ [ 0, 0, 1,], [ 0, 1, 0,], [ 1, 0, 0,],]

[waterz_params]
scoring_function = "random"

[seg_params.cellpose_params]
cellprob_threshold = -6
flow3D_smooth = 1
do_3D = true
batch_size = 32
flow_threshold = 0.4
