raw_base_dir = "Y:/jennifer/mhat/data/"
input_base_dir = "Y:/jennifer/mhat/experiments/"
output_base_dir = "Y:/jennifer/mhat/experiments/"
experiment = "NC281-sparse-label"
dataset = "02_nuclei_denoised_train"
seg_result = "2026-07-02_10-32-29"
flow_result = "2026-07-02_10-43-07"
use_lk = false
drift_distance = [ 0.0, 3.0, 6.0,]
drift_weight = 0.0
drift_constant = -2000.0
area_weight = 0.0
area_constant = 0.0
intensity_weight = 0.0
intensity_constant = 0.0
curvature_weight = 0.0
curvature_constant = 0.0
cohesion_weight = 0
cohesion_constant = 0
adhesion_weight = 0
adhesion_constant = 0
appear_constant = 50.0
disappear_constant = 50.0
max_children = 3
merges = false
divisions = false
min_merge_cost = 0.0
max_merge_cost = 1.0
max_edge_distance = 35
size_threshold = 0
ablate_cohesion_adhesion = false
ablate_drift = false
ablate_area = false
ablate_intensity = false
exp_uid = "add_none_dc2000"
z_flow_conf_threshold = 1e-7
z_flow_min_pass_pixels = 10
