input_base_dir = "Y:/jennifer/mhat/experiments/"
output_base_dir = "Y:/jennifer/mhat/experiments/"
experiment = "Fluo-C3DL-MDA231"
dataset = "02_cells"
track_result = "2026-06-01_16-01-29"
metrics = [ "basic",]
matcher = "point"
match_threshold = 10
