# IO
input_base_dir = "Y:/jennifer/mhat/experiments/"
output_base_dir = "Y:/jennifer/mhat/experiments/"
experiment = "NC281-Fl2mSiH2B"
dataset = "03_nuclei"

track_result = "2026-02-25_13-52-36"

# Eval settings
iou_threshold = 0.25
match_threshold = 10
