input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
experiment = "Fluo-C3DL-MDA231"
dataset = "02_cells"
track_result = "gt_amount/stage2_solves/gtm_C_b0131_s8"
metrics = [ "ctc", "track_overlap",]
matcher = "ctc"
ctc_gt = "02_GT"
