# IO
input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/segmentation/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/tracking/"
dataset = "mixin25"

# ILP params
drift = 0.0
drift_weight = 0.0
drift_constant = 0.0
area_weight = 0.5
area_constant = 0
cohesion_weight = -10
cohesion_constant = -250
adhesion_weight = -100
adhesion_constant = 0
appear_constant = 200.0
disappear_constant = 200.0

# cand graph creation params
min_merge_score = 0.0
max_merge_score = 0.5
max_edge_distance = 50

size_threshold = 50
