raw_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/data/"
input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
experiment = "Fluo-C3DL-MDA231"
dataset = "01_cells"
seg_result = "fs1cpm6_seg_noaff_wzfix"
flow_result = "2026-09-22_14-11-08"
use_lk = false
gt_data_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/tracking/Fluo-C3DL-MDA231/01_cells/gt_amount/gt_nodeid"
drift_distance = [ 0.0, 3.0, 6.0,]
drift_weight = 0.06442727250245715
drift_constant = -0.7491576516180234
area_weight = 0.49672066950046506
area_constant = -0.7491576516180234
intensity_weight = 0.0015085375911462694
intensity_constant = -0.7491576516180234
curvature_weight = 0.0
curvature_constant = 0.0
cohesion_weight = 0.0
cohesion_constant = 0.0
adhesion_weight = 0.0
adhesion_constant = 0.0
appear_constant = 0.5880803738403928
disappear_constant = 0.411919699733524
max_children = 3
merges = false
divisions = false
min_merge_cost = 0.0
max_merge_cost = 1.0
max_edge_distance = 60
size_threshold = 60
ablate_cohesion_adhesion = true
ablate_drift = false
ablate_area = false
ablate_intensity = false
ablate_curvature = true
ssvm_reg = 0.0383
ssvm_max_iter = 100
ssvm_eps = 1e-6
iogt_threshold = 0.5
output_name = "ssvm_merge_ablation/no_affinities"
exp_uid = "ssvm_merge_ablation/no_affinities"
n_labeled_measured = 1864
effective_reg = 71.3912
