# IO
input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/data/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/segmentation/"
experiment = "HamiltonDBWetDryMirror"
dataset = "00_nuclei"

overwrite = false

# segmentation parameters
[seg_params]
seg_method = "otsu"
spot_sigma = 0.5
outline_sigma = 0.5

[seg_params.cellpose_params]
# flow_threshold = 0.4
# cellprob_threshold = -3.0
# batch_size = 32
# do_3D = true