# IO
raw_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/data/"
input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
experiment = "Fluo-C3DL-MDA231"
dataset = "01_cells"

seg_result = "2026-04-03_11-09-49"
flow_result = "2026-02-17_15-55-00"
use_lk = false

# ILP params - MDA231 ablation baseline (exp_uid: 2026-04-15_09-42-38)
drift_distance = [ 0.0, 3.0, 6.0,]
drift_weight = 57.0
drift_constant = -2000.0
area_weight = 1730.0
area_constant = -1500.0
intensity_weight = 4.0
intensity_constant = -1000.0
curvature_weight = 0.0
curvature_constant = 0.0
cohesion_weight = 2000.0
cohesion_constant = 0.0
adhesion_weight = -1000.0
adhesion_constant = 0.0
appear_constant = 200.0
disappear_constant = 200.0

# cand graph creation params
max_children = 3
merges = false
divisions = false
min_merge_cost = 0.0
max_merge_cost = 1.0
max_edge_distance = 60
size_threshold = 60

# Confidence-based Z flow filtering
z_flow_conf_threshold = 0.0
z_flow_min_pass_pixels = 10

# Ablation flags
ablate_cohesion_adhesion = false
ablate_drift = false
ablate_area = false
ablate_intensity = false
