# IO
input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
experiment = "NC281-Fl2mSiH2B"
dataset = "00_nuclei"

seg_result = "2026-01-15_14-27-10"

# ILP params
drift_distance = 8.0
drift_weight = 1.0
drift_constant = -100.0
area_weight = 5.0
area_constant = -10.0
cohesion_weight = -3000
cohesion_constant = -100
adhesion_weight = -10
adhesion_constant = -100
appear_constant = 200.0
disappear_constant = 200.0

# cand graph creation params
max_children = 3
min_merge_score = 0.0
max_merge_score = 0.5
# max distance traveled between frames
max_edge_distance = 25

# fragments smaller than size_threshold will be ignored
size_threshold = 75
