input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
experiment = "NC281-sparse-label"
dataset = "02_nuclei_denoised_test"
track_result = "gt_amount/stage2_solves/gt2_C_b0196_s3"
metrics = [ "basic", "track_overlap",]
matcher = "point"
match_threshold = 10
