raw_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/data/"
input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
experiment = "Fluo-C2DL-Huh7"
dataset = "02_cells"
seg_result = "huh7seg_final_norm87"
flow_result = "2026-10-06_16-29-01"
verbose = true
drift_distance = [ 0.0, 3.0, 6.0,]
max_children = 5
merges = false
divisions = true
min_merge_cost = 0.0
max_merge_cost = 1.0
max_edge_distance = 50
size_threshold = 1000
z_flow_conf_threshold = 1e-7
z_flow_min_pass_pixels = 10
drift_weight = 0.20097886709696405
drift_constant = -0.7777333484395471
area_weight = 0.08597057351098125
area_constant = -0.7777333484395471
intensity_weight = -0.13887592551755978
intensity_constant = -0.7777333484395471
curvature_weight = 0.0
curvature_constant = 0.0
cohesion_weight = -0.07096207146971485
cohesion_constant = 0.05928301571213018
adhesion_weight = 0.310217533223556
adhesion_constant = 0.05928301571213018
division_weight = 0.14532257082038716
appear_constant = 0.166417770847411
disappear_constant = 0.2777878866131639
exp_uid = "huh7ssvm02_official"
