# IO
data_dir = "/groups/sgro/sgrolab/jennifer/cryolite/John/"
dataset = "251120_1613_NC281-Fl2mSiH2B_250cryo_20XWI_volMov_imersolpt2"
channel = 3
z_slice = 33

# optical flow params
downsample_factor = 2
pyr_scale = 0.5
levels = 3
winsize = 15
iterations = 8
poly_n = 5
poly_sigma = 1.2

# hyper params
enhance_contrast = true
temporal_smoothing = true
temporal_smoothing_sigma = 0.7
frame_averaging = 3

# display params
color_wheel = true
