# IO
input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/data/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/opticalflow/"
experiment = "NC281-Fl2mSiH2B"
dataset = "00_nuclei"

rerun_uid = ""

# display params
color_wheel = true

# 2D flow parameters
[2d]
do_2d = true
downsample_factor = 2
pyr_scale = 0.5
levels = 3
winsize = 15
iterations = 8
poly_n = 5
poly_sigma = 1.2
[2d.hyperparams]
enhance_contrast = true
temporal_smoothing = true
temporal_smoothing_sigma = 0.7
frame_averaging = 3

# 3D flow parameters
[3d]
do_3d = true
downsample_factor = [1, 1, 1]
pyr_scale = 0.5
levels = 3
winsize = [5, 15, 15]
iterations = 8
poly_n = 3
poly_sigma = [0.37, 1.2, 1.2]
filter_type = "gaussian"
presmoothing = 0.1
[3d.hyperparams]
enhance_contrast = true
temporal_smoothing = true
temporal_smoothing_sigma = 0.7
frame_averaging = 5

# lucas kanade parameters
[lucaskanade]
do_lucaskanade = true
pyr_scale = 0.5
levels = 3
winsize = 15
iterations = 8
tau = 0.1
alpha = 0.1
filter_type = "gaussian"
presmoothing = 0.1
[lucaskanade.hyperparams]
enhance_contrast = true
temporal_smoothing = true
temporal_smoothing_sigma = 0.7
frame_averaging = 5
