# IO
input_base_dir = "/path/to/experiments/"
output_base_dir = "/path/to/experiments/"
experiment = "experiment_1"
dataset = "dataset_1"
flow_result = "3d"
exp_uid = "flow_result"

# Metadata
xy_scale = 0.5
z_scale = 2.0
t_scale = 1.0
xyz_scale_unit = 'µm'
t_scale_unit = 'min'

# Thresholding
confidence_percentile = 90

# Visualization
z_slice = 2
gap = 2
quiver_scale = 1
scale_bar_velocity = 10

# Movie settings
fps = 5