input_base_dir = "Y:/jennifer/mhat/experiments/"
output_base_dir = "Y:/jennifer/mhat/experiments/"
ctc_gt = "02_GT"
metrics = [ "ctc",]
matcher = "ctc"
experiment = "Fluo-C3DL-MDA231"
dataset = "02_cells"
track_result = "negctrl_test"
