raw_base_dir = "Y:/jennifer/mhat/data/"
input_base_dir = "Y:/jennifer/mhat/experiments/"
output_base_dir = "Y:/jennifer/mhat/experiments/"
experiment = "Fluo-C3DL-MDA231"
dataset = "02_cells"
seg_result = "2026-05-29_10-47-41"
flow_result = "2026-05-29_10-59-37"
use_lk = false
drift_distance = [ 0.0, 3.0, 6.0,]
drift_weight = 0.0
drift_constant = 0.0
area_weight = 0.0
area_constant = 0.0
intensity_weight = 0.0
intensity_constant = 0.0
curvature_weight = 0.0
curvature_constant = 0.0
cohesion_weight = 0.0
cohesion_constant = 0.0
adhesion_weight = 0.0
adhesion_constant = 0.0
appear_constant = 200.0
disappear_constant = 200.0
max_children = 3
merges = false
divisions = false
min_merge_cost = 0.0
max_merge_cost = 1.0
max_edge_distance = 60
size_threshold = 60
base_edge_constant = -1000.0
exp_uid = "2026-06-25_15-32-46"
