raw_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/data/"
input_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
output_base_dir = "/groups/sgro/sgrolab/jennifer/mhat/experiments/"
experiment = "Fluo-C3DL-MDA231"
dataset = "02_cells"
seg_result = "fs1cpm6_seg_base_wzfix"
flow_result = "2026-09-22_14-13-30"
use_lk = false
drift_distance = [ 0.0, 3.0, 6.0,]
drift_weight = 0.07758564007661481
drift_constant = -0.6930381720350597
area_weight = 0.45854435218423045
area_constant = -0.6930381720350597
intensity_weight = 8.26967410669237e-5
intensity_constant = -0.6930381720350597
curvature_weight = 0.0
curvature_constant = 0.0
cohesion_weight = -0.14432162077499494
cohesion_constant = -0.06575133058293536
adhesion_weight = 0.13720587486418695
adhesion_constant = -0.06575133058293536
appear_constant = 0.6523692655107917
disappear_constant = 0.4862499805138078
max_children = 3
merges = false
divisions = false
min_merge_cost = 0.0
max_merge_cost = 1.0
max_edge_distance = 60
size_threshold = 60
exp_uid = "gt_amount/stage3_solves_regen/regsweep_r05"
